### PR TITLE
Set-up-hello-microverse-project

### PR DESCRIPTION
**Pull request by Donard97**
This is my first project for Microverse. I had to create a repository here on Github and then I created a new branch to do the requirements. I added a .gitignore file to ignore files that are not relevant. Then I created 3 files an HTML file, a CSS file, and a test.md file. The last file is ignored by git and is not present in my Github repository. At the end of my project, I added another folder with GitHub actions in it which are ignored too by Github.

### CODE REVIEW

**Review by AshakaE — CHANGES_REQUESTED** [review]
Hi @Donard97 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [x] Please set up your GitHub actions for  linters, follow this link for steps .[https://github.com/microverseinc/linters-config/tree/master/html-css](html-css)
- [x] Please add a descriptive message for your pull request.
- [x] Kindly add your `.gitignore` file in the root directory of your project with the required files to be ignored, right now you have it in a folder, also remember to add the `node_modules` folder to the `.gitignore` file as well.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Donard97** [comment]
This is my first project for Microverse. I had to create a repository here on Github and then I created a new branch to do the requirements. I added a .gitignore file to ignore files that are not relevant. Then I created 3 files an HTML file, a CSS file, and a test.md file. The last file is ignored by git and is not present in my Github repository. At the end of my project, I added another folder with GitHub actions in it which are ignored too by Github.

**Review by ZawadiSumba66 — CHANGES_REQUESTED** [review]
#### Hi @Donard97 👋 👋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- [ ] As pointed out by the previous, you ought to add linters files to check for linters errors in your code. Please fix this.
- [x] Good job adding the `.gitignore` file to the root directory however it should contain a 
`test.MD` file and a `node_modules` folder. Please remove the `.github/workflows`  from .gitignore since it is meant to check if the linters are running on Github.
- [x] I can see that you tried giving a description of your pull request in the comment section below. However, pull requests descriptions are normally written at the very top comment box. Refer to this screenshot for more guidance.
image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Donard97** [comment]
This is my first project for Microverse. I had to create a repository here on Github and then I created a new branch to do the requirements. I added a .gitignore file to ignore files that are not relevant. Then I created 3 files an HTML file, a CSS file, and a test.md file. The last file is ignored by git and is not present in my Github repository. At the end of my project, I added another folder with GitHub actions in it which are ignored too by Github.

**Review by Shaher-11 — APPROVED** [review]
#### Hello @Donard97,

# Congratulations! 🎉 
#### Your project is approved!  There is nothing else to say other than... it's time to merge it :muscle: :muscle::muscle:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

**Pull request merged**
